_welcome:
    pattern:  /
    defaults: { _controller: LoginLoginBundle:Default:index }
login_page:
    pattern:  /login
    defaults: { _controller: LoginLoginBundle:Default:index }
logout_action:
    pattern:  /logout
    defaults: { _controller: LoginLoginBundle:Page:logout }