_welcome:
    pattern:  /
    defaults: { _controller: BlogBlogBundle:Default:index }
login_page:
    pattern:  /blog
    defaults: { _controller: LoginLoginBundle:Default:index }
logout_action:
    pattern:  /logout
    defaults: { _controller: LoginLoginBundle:Default:logout }